name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: install bash.ly and build
      run: |
        gem install bashly
        bashly generate
        
    - uses: actions/upload-artifact@v3
      with:
        name: generated-executive-script
        path: gs

  test-linux:
    name: Test install dependency
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: generated-executive-script
        path: gs
    - name: Install dev
      run: |
        cd gs
        sudo bash ./gs install-deps dev
  test-macos:
    name: Test install dependency
    needs: [build]
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: generated-executive-script
          path: gs
      - name: Install dev
        run: |
          ls -la gs
          cd gs
          brew install bash
          alias bash=$(brew --prefix)/bin/bash
          bash ./gs install-deps dev