name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3

    - name: Install bash.ly and build
      run: |
        gem install bashly
        bashly generate

    - uses: actions/upload-artifact@v3
      with:
        name: generated-executive-script
        path: gs

  test-on-ubuntu-macos:
    name: Test install dependency
    needs: [generate]
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: generated-executive-script
        path: gs

    - name: Install dev
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install bash
            alias bash=$(brew --prefix)/bin/bash
        fi
        sudo mkdir /opt/graphscope
        sudo chown -R $(id -u):$(id -g) /opt/graphscope
        bash gs/gs install-deps dev --install-prefix /opt/graphscope --v6d-version v0.14.5
        cat ~/.graphscope_env

    - name: Get GraphScope Source
      run: git clone --depth=1 https://github.com/alibaba/graphscope

    - name: Build analytical engine
      run: source ~/.graphscope_env && cd graphscope && make analytical

    - name: Build interactive engine
      run: source ~/.graphscope_env && cd graphscope && make interactive

    - name: Build learning engine
      run: source ~/.graphscope_env && cd graphscope && make learning

    - name: Build coordinator
      if: false  # Known issue with pyarrow 6.0, remove after fixed
      run: |
        cd graphscope
        source ~/.graphscope_env
        make coordinator

    - name: Build client
      if: false
      run: |
        cd graphscope
        source ~/.graphscope_env
        make client

  test-on-centos-8:
    needs: [ generate ]
    runs-on: ubuntu-22.04
    container:
      image: centos:latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: generated-executive-script
          path: gs

      - name: Install dev
        run: |
          bash gs/gs install-deps dev --install-prefix /opt/graphscope --v6d-version v0.14.5
          cat ~/.graphscope_env

      - name: Get GraphScope Source
        run: git clone --depth=1 https://github.com/alibaba/graphscope

      - name: Build analytical engine
        run: source ~/.graphscope_env && cd graphscope && make analytical

      - name: Build interactive engine
        run: source ~/.graphscope_env && cd graphscope && make interactive

      - name: Build learning engine
        run: source ~/.graphscope_env && cd graphscope && make learning

  test-on-centos-7:
    needs: [ generate ]
    runs-on: ubuntu-22.04
    container:
      image: centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: generated-executive-script
          path: gs

      - name: Install dev
        run: |
          bash gs/gs install-deps dev --install-prefix /opt/graphscope --v6d-version v0.14.5
          cat ~/.graphscope_env

      - name: Get GraphScope Source
        run: git clone --depth=1 https://github.com/alibaba/graphscope

      - name: Build analytical engine
        run: source ~/.graphscope_env && cd graphscope && make analytical

      - name: Build interactive engine
        run: source ~/.graphscope_env && cd graphscope && make interactive

      - name: Build learning engine
        run: source ~/.graphscope_env && cd graphscope && make learning
