name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: install bash.ly and build
      run: |
        gem install bashly
        bashly generate
        
    - uses: actions/upload-artifact@v3
      with:
        name: generated-executive-script
        path: gs

  test:
    name: Test install dependency
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: generated-executive-script
        path: gs
    - name: Prerequisites
      if: matrix.os == 'macos-latest'
      run: |
        brew install bash
    - name: Install dev
      run: |
        ls -la gs
        cd gs
        alias bash=$(brew --prefix)/bin/bash || true
        sudo bash ./gs install-deps dev
