name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: install bash.ly and build
      run: |
        gem install bashly
        bashly generate
        
    - uses: actions/upload-artifact@v3
      with:
        name: generated-executive-script
        path: gs

  test-linux:
    name: Test install dependency
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: generated-executive-script
        path: gs
    - name: Install dev
      run: |
        cd gs
        sudo bash ./gs install-deps dev
        sudo chown 1001:121 /root/.graphscope_dev
        # TODO: Using sudo will cause the env output location to root home
        cat /root/.graphscope_env

    - name: Get GraphScope Source
      run: git clone --depth=1 https://github.com/alibaba/graphscope

    - name: Build analytical engine
      run: |
        cd graphscope
        source /root/.graphscope_dev
        make analytical

    - name: Build interactive engine
      run: |
        cd graphscope
        source /root/.graphscope_dev
        make interactive

    - name: Build learning engine
      run: |
        cd graphscope
        source /root/.graphscope_dev
        make learning
    - name: Build coordinator
      run: |
        cd graphscope
        source /root/.graphscope_dev
        make coordinator

    - name: Build client
      run: |
        cd graphscope
        source /root/.graphscope_dev
        make client

  test-macos:
    name: Test install dependency (macos-latest)
    needs: [build]
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: generated-executive-script
          path: gs
      - name: Install dev
        run: |
          ls -la gs
          cd gs
          brew update
          brew install bash
          alias bash=$(brew --prefix)/bin/bash
          # Doesn't have permission on /opt/graphscope
          # and one could not use brew with sudo
          bash ./gs install-deps dev --prefix $HOME/graphscope
          cat ~/.graphscope_env

    - name: Get GraphScope Source
      run: git clone --depth=1 https://github.com/alibaba/graphscope

    - name: Build analytical engine
      run: |
        cd graphscope
        source ~/.graphscope_dev
        make analytical

    - name: Build interactive engine
      run: |
        cd graphscope
        source ~/.graphscope_dev
        make interactive

    - name: Build learning engine
      run: |
        cd graphscope
        source ~/.graphscope_dev
        make learning
    - name: Build coordinator
      run: |
        cd graphscope
        source ~/.graphscope_dev
        make coordinator

    - name: Build client
      run: |
        cd graphscope
        source ~/.graphscope_dev
        make client

