name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: Install bash.ly and build
      run: |
        gem install bashly
        bashly generate

    - name: Insert friendly prompt
      run: |
        sed -i '8i \  \printf "If you are using MacOS, run the following command to get a newer bash: \\n  brew install bash && bash\\n" >&2' ./gs
        
    - uses: actions/upload-artifact@v3
      with:
        name: generated-executive-script
        path: gs

  test-linux:
    name: Test install dependency
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: generated-executive-script
        path: gs
    - name: Install dev
      if: runner.os == 'Linux'
      run: |
        cd gs
        # TODO: Using sudo will cause the env output location to root home
        sudo bash ./gs install-deps dev
        sudo cp /root/.graphscope_env ~/.graphscope_env
        sudo chown $(id -u):$(id -g) ~/.graphscope_env
        ls -la ~/.graphscope_dev
        cat ~/.graphscope_env

    - name: Install dev
      if: runner.os == 'macOS'
      run: |
        cd gs
        brew update
        brew install bash
        alias bash=$(brew --prefix)/bin/bash
        # Doesn't have permission on /opt/graphscope
        # and one could not use brew with sudo
        bash ./gs install-deps dev --install-prefix $HOME/graphscope
        cat ~/.graphscope_env

    - name: Get GraphScope Source
      run: |
        git clone --depth=1 https://github.com/alibaba/graphscope

    - name: Build analytical engine
      run: |
        cd graphscope
        source ~/.graphscope_env
        make analytical

    - name: Build interactive engine
      run: |
        cd graphscope
        source ~/.graphscope_env
        make interactive

    - name: Build learning engine
      run: |
        cd graphscope
        source ~/.graphscope_env
        make learning

    - name: Build coordinator
      if: false  # Known issue with pyarrow 6.0, remove after fixed
      run: |
        cd graphscope
        source ~/.graphscope_env
        make coordinator

    - name: Build client
      if: false
      run: |
        cd graphscope
        source ~/.graphscope_env
        make client
